### ISSUE TITLE
How to write bitbucket pipeline for deploying my angular universal app?

### ISSUE THREAD

**Issue by amand4d** [angular/universal#1765]
I am trying to deploy my angular universal app on server through bitbucket pipeline. I have written scripts in bitbucket-pipelines.yml as follows:

```
pipelines:
  default:
    - step:
        name: Build app
        caches:
          - node
        script:
          - npm install
          - npm install -g @angular/cli
          - npm run build:ssr
          - npm run serve:ssr
        artifacts:
          - dist/**
```

My package.json has following scripts:

```
"scripts": {
        "ng": "ng",
        "start": "ng serve -c=dev -o",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
        "serve:ssr": "node dist/server.js",
        "build:client-and-server-bundles": "ng build --prod && ng run my-app:server",
        "webpack:server": "webpack --config webpack.server.config.js --progress --colors"
    },
```

When `npm run serve:ssr` executes, I see that it gives same output as on localhost i.e. `Node server listening on http://localhost:4000`. It gets stuck at this point. What am I doing wrong here?
