### ISSUE TITLE
SSR not working with HTTPS API URL

### ISSUE THREAD

**Issue by ranjitnadar** [angular/universal#856]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
```
- [ ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [ ] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 4.1
- Browser: [all  ]
- Language: [TypeScript 2.3.1]
- OS:  [all ]
- Platform: [NodeJs |  PHP]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

SSR fail when we using https api url for seo meta information. Using http working perfect.

Any solution please help me regards this.

**Comment by Toxicable** [comment]
How does it fail?

**Comment by ranjitnadar** [comment]
Using http powered api SSR working perfectly. But can not figure out with SSR Https why its not working

Bellow are the screen shots It render on client side when i inspect in google chrome, But i do the view source code of it Can not see any meta tag rendering there.

Inspect in chrome

![8kbtc](https://user-images.githubusercontent.com/3095820/33511360-619c6aba-d73f-11e7-9e7f-fb2bf2c824a0.jpg)


view source code in chrome

![8pcnu](https://user-images.githubusercontent.com/3095820/33511358-5aa3528c-d73f-11e7-8270-742b20f3489c.jpg)


As you can see the Difference here the last to meta tag render on client side on inspect but are not there when i view source code when i use SSR Https, But using SSR Http every thing work fine.


Using https://angular.io/api/platform-browser/Meta

My code:
<img width="726" alt="wbkze" src="https://user-images.githubusercontent.com/3095820/33511356-50376fea-d73f-11e7-82dc-939554c041c5.png">

**Comment by hiepxanh** [comment]
please, provide the network recording in your network recording (example below), I believe some request are pending at status column.

![image](https://user-images.githubusercontent.com/16970990/33521914-5ce3ba40-d812-11e7-945f-b7f10cded60c.png)

**Comment by salih0313** [comment]
@ranjitnadar I am also facing same issues. Did you find any solution?

**Comment by ranjitnadar** [comment]
Unable to find solution:
We tried installing ssl in server side rendering unable to resolve this issue.
For now we are using http api url for meta information rendering.

**Comment by patrykp57** [comment]
I have the same issue, but it only doesn't work on home page. I'm using https on whole site + on api. When I'm trying to enter home page, AuthGuard from Angular redirect me from https://example.org to https://example.org/en and then I can see Elements in Chrome Dev Tools, but when I'm trying to inspect view source by right mouse click, it's empty (like without Universal). When I'm turning off HTTPS redirect which I did like that

```
app.use(forceSsl);

  app.use('/',function(req, res, next){
    console.log(req.headers);
    next();
 });
```
Home page view source is working good. 
Any solution ?

**Comment by jeyachanthuruj** [comment]
Guys, Any update on this topic. Because I'm also facing this problem.

**Comment by Chipintoza** [comment]
Any update on this?

**Comment by Toxicable** [comment]
I havn't been able to reproduce this issue myself.
Could someone provide a minimal reproduction for this issue?

**Comment by Toxicable** [comment]
@Baedonghee Sorry but there isn't much we can do without a minimal reproduction of the issue.
Are you able  to put one together for us?

**Comment by Baedonghee** [comment]
app.get('/', (req, res) => {
  res.render('index', {
    req,
    res,
    providers: [
      {
        provide: 'serverUrl',
        useValue: `${req.protocol}://${req.get('host')}`
      }
    ]
  });
});
app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP)
  ]
}));
app.set('view engine', 'html');
app.set('views', join(DIST_FOLDER));

app.use('/api/user', userRouter);
app.get('*', (req, res) => {
  res.render('index', {
    req,
    res,
    providers: [
      {
        provide: 'serverUrl',
        useValue: `${req.protocol}://${req.get('host')}`
      }
    ]
  });
});

server.ts 

this.store.dispatch(new CoreActions.GetUserList(this.queryParams.toString()));
this.userListState = this.store.select('userlist');

app.component.ts


http seo ok.... but https seo not working....

**Comment by ssatz** [comment]
facing the same issue using docker.  The app throwing 

>  message: 'Http failure response for (unknown url): 0 Unknown Error',

This is working perfectly in my local environment using self signed certificate. 
When the api changed to https am getting above error. 

Hosted on digital ocean

Structure of docker

Laravel (Api http://api.app.lo)
Angular (http://app.lo)
nginx (Nginx Configuration)

docker-compose.yml

```
version: '3'
services:

  laravel:
    build: ./laravel/docker/php
    depends_on:
      - database
    expose:
      - 9000  
    volumes:
      - ./laravel:/var/www/laravel
      - $HOME/.composer/:$HOME/.composer/
    environment:
      - "DB_HOST=database"    #mysql service name - database
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_PASSWORD=homestead"
      - "REDIS_HOST=cache"
      - "REDIS_PORT=6379"
      - "APP_URL=http://app.lo"

  angular:
    build: ./angular
    expose:
      - 3000
    volumes:
      - ./angular:/var/www/angular 
    depends_on:
      - laravel

  web:
    build: ./nginx
    volumes:
      - ./:/var/www/
    ports:
      - 80:80
      - 443:443
    links:
      - laravel:laravel
      - angular:angular
    depends_on:
      - laravel
      - angular
    environment:
      - VIRTUAL_HOST=app.lo, portal.app.lo , api.app.lo, shop.app.lo  
   networks:
      default:
         aliases:
            - api.app.lo

  database:
    build: ./laravel/docker/mariadb
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=homestead"
    ports:
      -  3306:3306

  mongodb:
   image: mongo:latest
   container_name: mongo
   restart: always
   volumes:
     -  mongo:/data/db
   ports:
      - 27017:27017
   command: --storageEngine wiredTiger

  cache:
    image: redis:4.0-alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
  nodejs:
    build: ./laravel/docker/nodejs
    volumes:
      - ./:/var/www/laravel

volumes:
  mysqldata:
  mongo:

networks:
  default:
    external:
      name: nginx-proxy
```
any solution?
